# Generated by Django 3.1.6 on 2021-02-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminmore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminMore',
        ),
    ]
