# Generated by Django 3.1.6 on 2021-02-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
