# Generated by Django 3.1.6 on 2021-02-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_app', '0001_initial'),
        ('book_shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lend_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.lendperiod'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book_shelf.publisher'),
        ),
    ]
