# Generated by Django 3.1.6 on 2021-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0002_auto_20210223_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.CharField(choices=[], default='Paper', max_length=50),
        ),
    ]
