# Generated by Django 3.1.6 on 2021-02-24 22:47

import book_shelf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0003_book_book_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=book_shelf.models.book_image_directory),
        ),
    ]
