# Generated by Django 3.1.6 on 2021-02-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0003_book_book_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.CharField(choices=[('Audiobook', 'Audiobook'), ('PDF', 'PDF'), ('Paper', 'Paper'), ('E-book', 'E-book')], default='Paper', max_length=50),
        ),
    ]
