# Generated by Django 3.1.6 on 2021-02-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='users.customer'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_debt', to='users.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryworkingtime',
            unique_together={('library', 'day_of_week')},
        ),
    ]
