# Generated by Django 3.1.6 on 2021-02-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20210222_0517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='libraryworkingtime',
            options={'verbose_name_plural': 'Library working time'},
        ),
    ]
