# Generated by Django 3.1.6 on 2021-02-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20210225_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fine',
            name='lend_period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='library_app.lendperiod'),
        ),
    ]
