# Generated by Django 3.1.6 on 2021-02-22 22:47

from django.db import migrations, models
import library_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20210222_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=library_app.models.library_image_directory),
        ),
    ]
