# Generated by Django 3.1.6 on 2021-02-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('library_app', '0003_auto_20210301_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='users.customer')),
            ],
        ),
    ]
