# Generated by Django 3.1.6 on 2021-02-12 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20210211_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_amount', models.IntegerField()),
                ('days_amount', models.IntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
            options={
                'verbose_name': 'Lending period',
                'verbose_name_plural': 'Lending periods',
                'ordering': ['days_amount'],
                'get_latest_by': 'days_amount',
            },
        ),
        migrations.DeleteModel(
            name='LendPeriods',
        ),
    ]
