# Generated by Django 3.1.6 on 2021-02-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20210223_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
