# Generated by Django 3.1.6 on 2021-02-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_auto_20210212_0420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookprofile',
            options={'get_latest_by': 'days_amount', 'ordering': ['days_amount'], 'verbose_name': 'Book profile', 'verbose_name_plural': 'Book profiles'},
        ),
    ]
