# Generated by Django 3.1.6 on 2021-02-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprofile',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.publisher'),
        ),
    ]
