# Generated by Django 3.1.6 on 2021-02-12 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_bookprofile_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_profile', to='library_app.book'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
