# Generated by Django 3.1.6 on 2021-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_auto_20210212_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprofile',
            name='book_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='book_amount_total',
            field=models.PositiveIntegerField(),
        ),
    ]
