# Generated by Django 3.1.6 on 2021-02-15 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20210215_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateField(default=datetime.date(2021, 2, 15)),
        ),
    ]
