# Generated by Django 3.1.6 on 2021-02-15 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_auto_20210215_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
