# Generated by Django 3.1.6 on 2021-02-15 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_auto_20210215_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
