# Generated by Django 3.1.6 on 2021-02-15 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_auto_20210215_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.book'),
        ),
    ]
